name: CI
on:
  push:
    branches:
      - main
jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ["3.6", "3.9"]
          architecture: 'x64'
      - run: |
          pytest -v
          find . -name \*.py -exec pycodestyle {} +